site_name: The Eternal City Wiki
site_description: Community-maintained wiki for The Eternal City MUD
site_url: ""

theme:
  name: material
  variant: classic
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit

nav:
  - Play Now:
      - Home: index.md
  - Community:
      - About the Wiki: about.md
  - Getting Started:
      - Armor: armor.md
  - The Game World:
      - Combat: mechanics/combat.md
  - Crafting:
      - Jewelry Crafting: crafting/jewelry.md
      - Leatherworking: crafting/leatherworking.md
  - Roleplaying:
      - About the Wiki: about.md
  - Getting Around:
      - Home: index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/tec.css
