from html.parser import HTMLParser
from pathlib import Path
import json


# The editor preview uses exactly the stylesheets and page-content scripts a
# built page loads, so the preview cannot drift from the live site.
# tec-preview.css is added last and must only contain fixes for the preview frame.
PREVIEW_OVERRIDES = "/stylesheets/tec-preview.css"
OUTPUT = Path("admin") / "tec-preview-assets.js"

# Site scripts that register page enhancers (docs/javascripts/tec-page-enhancers.js).
ENHANCER_REGISTRY = "tec-page-enhancers.js"
ENHANCER_MARKER = "TEC.addPageEnhancer("


class _PageAssets(HTMLParser):
    def __init__(self):
        super().__init__()
        self.styles = []
        self.scripts = []
        self._in_head = False
        self._in_style = False
        self._css = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "head":
            self._in_head = True
        elif tag == "script" and attrs.get("src"):
            self.scripts.append(attrs["src"])
        elif self._in_head and tag == "link" and "stylesheet" in (attrs.get("rel") or "").split():
            self.styles.append({"href": attrs.get("href", "")})
        elif self._in_head and tag == "style":
            self._in_style = True
            self._css = []

    def handle_endtag(self, tag):
        if tag == "head":
            self._in_head = False
        elif tag == "style" and self._in_style:
            self._in_style = False
            self.styles.append({"css": "".join(self._css)})

    def handle_data(self, data):
        if self._in_style:
            self._css.append(data)


def _absolute(href):
    if href.startswith(("http://", "https://", "//", "/")):
        return href
    while href.startswith("./"):
        href = href[2:]
    return "/" + href


def _enhancer_scripts(site_dir, scripts):
    found = []
    for src in scripts:
        url = _absolute(src)
        if not url.startswith("/"):
            continue
        path = site_dir / url.lstrip("/")
        if not path.is_file():
            continue
        if path.name == ENHANCER_REGISTRY or ENHANCER_MARKER in path.read_text(encoding="utf-8", errors="replace"):
            found.append(url)
    return found


def on_post_build(config, **kwargs):
    site_dir = Path(config["site_dir"])
    page = site_dir / "index.html"

    parser = _PageAssets()
    parser.feed(page.read_text(encoding="utf-8"))

    if not any("href" in style for style in parser.styles):
        raise RuntimeError("preview_assets: no stylesheets found in %s; the editor preview would be unstyled" % page)

    lines = []
    for style in parser.styles:
        if "href" in style:
            lines.append("CMS.registerPreviewStyle(%s);" % json.dumps(_absolute(style["href"])))
        else:
            lines.append("CMS.registerPreviewStyle(%s, { raw: true });" % json.dumps(style["css"]))
    lines.append("CMS.registerPreviewStyle(%s);" % json.dumps(PREVIEW_OVERRIDES))

    scripts = _enhancer_scripts(site_dir, parser.scripts)
    if not scripts or not scripts[0].endswith("/" + ENHANCER_REGISTRY):
        raise RuntimeError("preview_assets: %s must load before the page enhancer scripts in %s" % (ENHANCER_REGISTRY, page))

    # Load the enhancer scripts in page order; they only register themselves here.
    lines.append("%s.forEach(function (src) {" % json.dumps(scripts))
    lines.append("  var script = document.createElement(\"script\");")
    lines.append("  script.src = src;")
    lines.append("  script.async = false;")
    lines.append("  document.head.appendChild(script);")
    lines.append("});")

    out = site_dir / OUTPUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Generated by hooks/preview_assets.py from the built site's pages. Do not edit.\n"
        + "\n".join(lines) + "\n",
        encoding="utf-8",
    )
