from html.parser import HTMLParser
from pathlib import Path
import json


# The editor preview loads exactly the stylesheets a built page loads, so the
# preview cannot drift from the live site. tec-preview.css is added last and
# must only contain fixes for the preview frame itself.
PREVIEW_OVERRIDES = "/stylesheets/tec-preview.css"
OUTPUT = Path("admin") / "tec-preview-styles.js"


class _HeadStyles(HTMLParser):
    def __init__(self):
        super().__init__()
        self.styles = []
        self._in_head = False
        self._in_style = False
        self._css = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "head":
            self._in_head = True
        elif self._in_head and tag == "link" and "stylesheet" in (attrs.get("rel") or "").split():
            self.styles.append({"href": attrs.get("href", "")})
        elif self._in_head and tag == "style":
            self._in_style = True
            self._css = []

    def handle_endtag(self, tag):
        if tag == "head":
            self._in_head = False
        elif tag == "style" and self._in_style:
            self._in_style = False
            self.styles.append({"css": "".join(self._css)})

    def handle_data(self, data):
        if self._in_style:
            self._css.append(data)


def _absolute(href):
    if href.startswith(("http://", "https://", "//", "/")):
        return href
    while href.startswith("./"):
        href = href[2:]
    return "/" + href


def on_post_build(config, **kwargs):
    site_dir = Path(config["site_dir"])
    page = site_dir / "index.html"

    parser = _HeadStyles()
    parser.feed(page.read_text(encoding="utf-8"))

    calls = []
    for style in parser.styles:
        if "href" in style:
            calls.append("CMS.registerPreviewStyle(%s);" % json.dumps(_absolute(style["href"])))
        else:
            calls.append("CMS.registerPreviewStyle(%s, { raw: true });" % json.dumps(style["css"]))

    if not any("href" in style for style in parser.styles):
        raise RuntimeError("preview_styles: no stylesheets found in %s; the editor preview would be unstyled" % page)

    calls.append("CMS.registerPreviewStyle(%s);" % json.dumps(PREVIEW_OVERRIDES))

    out = site_dir / OUTPUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Generated by hooks/preview_styles.py from the built site's <head>. Do not edit.\n"
        + "\n".join(calls) + "\n",
        encoding="utf-8",
    )
